In [1]:
import os
import sys; sys.path.append("/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/python") # to load packages
import training_utils as utils
import numpy as np
reload(utils)
import preprocessing_utils as preprocessing
reload(preprocessing)
import plotting_utils as plotting
reload(plotting)
import optimization_utils as optimization
reload(optimization)
import postprocessing_utils as postprocessing
reload(postprocessing)


Welcome to JupyROOT 6.13/02


<module 'postprocessing_utils' from '/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/python/postprocessing_utils.pyc'>

In [2]:
reload(utils)
reload(preprocessing)
reload(plotting)
reload(optimization)
reload(postprocessing)
#ntuples = '2016'
ntuples = '2017'
# "%" sign allows to interpret the rest as a system command
%env data=$utils.IO.ldata$ntuples
files = ! ls $data | sort -t_ -k 3 -n
#pick only SM
#signal = [s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_2016.root" in s]
#diphotonJets = [s for s in files if "DoubleEG_2016.root" in s]
#signal = [s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_2017.root" in s]
#
signal = [s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_st_cuts.root" in s]
diphotonJets = [s for s in files if "output_DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa_st_cuts.root" in s]
gJets_lowPt = [s for s in files if "output_GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts.root" in s]
gJets_highPt = [s for s in files if "output_GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts.root" in s]
#
#signal = [s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_st_cuts_ptMjj.root" in s]
#diphotonJets = [s for s in files if "output_DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa_st_cuts_ptMjj.root" in s]
#gJets_lowPt = [s for s in files if "output_GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts_ptMjj.root" in s]
#gJets_highPt = [s for s in files if "output_GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts_ptMjj.root" in s]
#
#diphotonJets = [s for s in files if "DoubleEG_2017.root" in s]
#signal = [s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph.root" in s]
#diphotonJets = [s for s in files if "DoubleEG.root" in s]
#signal = [s for s in files if "GluGluToHHTo2B2G_node_SM" in s]
diphotonJets = [s for s in files if "DiPhotonJetsBox_" in s]
gJets_lowPt = [s for s in files if "GJet_Pt-20to40" in s]
gJets_highPt = [s for s in files if "GJet_Pt-40" in s]
#ggH = [s for s in files if "GluGluHToGG" in s]
#vbf = [s for s in files if "VBFHToGG" in s]
#VH = [s for s in files if "VHToGG" in s]
#bbH = [s for s in files if "bbHToGG_M-125_4FS_yb2" in s] #is this correct?
#ttH = [s for s in files if "ttHToGG" in s]

#Data= [s for s in files if "DoubleEG_2016.root" in s]
#Data= [s for s in files if "DoubleEG_2017.root" in s]
Data= [s for s in files if "DoubleEG_2017_st_cuts.root" in s]
#Data= [s for s in files if "DoubleEG_2017_st_cuts_ptMjj.root" in s]
#Data= [s for s in files if "DoubleEG.root" in s]
#Data= [s for s in files if "DoubleEG" in s]

utils.IO.add_signal(ntuples,signal,1)
print diphotonJets
utils.IO.add_background(ntuples,diphotonJets,-1)
utils.IO.add_background(ntuples,gJets_lowPt,-2)
utils.IO.add_background(ntuples,gJets_highPt,-2)
#utils.IO.add_background(ntuples,ggH,-3)
#utils.IO.add_background(ntuples,vbf,-4)
#utils.IO.add_background(ntuples,VH,-5)
#utils.IO.add_background(ntuples,bbH,-6)
#utils.IO.add_background(ntuples,ttH,-7)

nBkg = len(utils.IO.backgroundName)

utils.IO.add_data(ntuples,Data,-10)

#add all nodes
nodes = []
#for i in range(2,14):
#    nodes.append([s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_2016"+str(i) in s])
##    nodes.append([s for s in files if "GluGluToHHTo2B2G_node_"+str(i) in s])
for i in range(len(utils.IO.backgroundName),len(utils.IO.backgroundName)+len(nodes)):
    utils.IO.add_background(ntuples,nodes[i-nBkg],-i) 
    

for i in range(len(utils.IO.backgroundName)):        
    print "using background file n."+str(i)+": "+utils.IO.backgroundName[i]
for i in range(len(utils.IO.signalName)):    
    print "using signal file n."+str(i)+": "+utils.IO.signalName[i]
print "using data file: "+ utils.IO.dataName[0]


env: data=/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017
['output_DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa_st_cuts.root']
using background file n.0: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/output_DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa_st_cuts.root
using background file n.1: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/output_GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts.root
using background file n.2: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/output_GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts.root
using signal file n.0: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_st_cuts.root
using data file: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/DoubleEG_2017_st_cuts.root


In [3]:
#use noexpand for root expressions, it needs this file https://github.com/ibab/root_pandas/blob/master/root_pandas/readwrite.py
#all the branches you want to save in new trees
#mva variables
#branch_names = 'leadingJet_bDis,subleadingJet_bDis,noexpand:fabs(CosThetaStar_CS),noexpand:fabs(CosTheta_bb),noexpand:fabs(CosTheta_gg)'.split(",")
#branch_names += 'noexpand:diphotonCandidate.Pt()/diHiggsCandidate.M(),noexpand:dijetCandidate.Pt()/diHiggsCandidate.M()'.split(",")
#branch_names += 'customLeadingPhotonIDMVA,customSubLeadingPhotonIDMVA,leadingPhotonSigOverE,subleadingPhotonSigOverE,sigmaMOverMDecorr,PhoJetMinDr'.split(",")
#standart of input values 
branch_names = 'absCosThetaStar_CS,absCosTheta_bb,absCosTheta_gg,PhoJetMinDr,customLeadingPhotonIDMVA,customSubLeadingPhotonIDMVA,leadingJet_DeepCSV,subleadingJet_DeepCSV,leadingPhotonSigOverE,subleadingPhotonSigOverE,sigmaMOverM,diphotonCandidatePtOverdiHiggsM,dijetCandidatePtOverdiHiggsM,leadingJet_bRegNNResolution,subleadingJet_bRegNNResolution,noexpand:sigmaMJets/Mjj'.split(",")
#st values with adding pt_gg/m_gg
#branch_names = 'absCosThetaStar_CS,absCosTheta_bb,absCosTheta_gg,PhoJetMinDr,customLeadingPhotonIDMVA,customSubLeadingPhotonIDMVA,leadingJet_DeepCSV,subleadingJet_DeepCSV,leadingPhotonSigOverE,subleadingPhotonSigOverE,sigmaMOverM,diphotonCandidatePtOverdiHiggsM,dijetCandidatePtOverdiHiggsM,leadingJet_bRegNNResolution,subleadingJet_bRegNNResolution,noexpand:sigmaMJets/Mjj,noexpand:leadingPhoton_pt/CMS_hgg_mass,noexpand:subleadingPhoton_pt/CMS_hgg_mass'.split(",")
#st values with adding pt_gg/m_gg, pt_jj/M_jj
#branch_names = 'absCosThetaStar_CS,absCosTheta_bb,absCosTheta_gg,PhoJetMinDr,customLeadingPhotonIDMVA,customSubLeadingPhotonIDMVA,leadingJet_DeepCSV,subleadingJet_DeepCSV,leadingPhotonSigOverE,subleadingPhotonSigOverE,sigmaMOverM,diphotonCandidatePtOverdiHiggsM,dijetCandidatePtOverdiHiggsM,leadingJet_bRegNNResolution,subleadingJet_bRegNNResolution,noexpand:sigmaMJets/Mjj,noexpand:leadingPhoton_pt/CMS_hgg_mass,noexpand:subleadingPhoton_pt/CMS_hgg_mass,noexpand:leadingJet_pt/Mjj,noexpand:subleadingJet_pt/Mjj,PhoJetotherDr'.split(",")

#mva output
#branch_names = 'HHTagger2017'.split(",")
#additional variables
#branch_names += 'noexpand:diphotonCandidate.M(),noexpand:dijetCandidate.M(),MX,isSignal'.split(",")


#branch_names = 'leadingJet_bDis,subleadingJet_bDis,noexpand:fabs(CosThetaStar_CS),noexpand:fabs(CosTheta_bb),noexpand:fabs(CosTheta_gg),noexpand:diphotonCandidate.Pt()/diHiggsCandidate.M(),noexpand:dijetCandidate.Pt()/diHiggsCandidate.M()'.split(",")
branch_names = [c.strip() for c in branch_names]
print branch_names

import pandas as pd
import root_pandas as rpd

# no need to shuffle here, we just count events
preprocessing.set_signals_and_backgrounds("bbggSelectionTree",branch_names,shuffle=False)
X_bkg,y_bkg,weights_bkg,X_sig,y_sig,weights_sig=preprocessing.set_variables(branch_names)

X_data,y_data,weights_data = preprocessing.set_data("bbggSelectionTree",branch_names)
X_data,y_data,weights_data = preprocessing.clean_signal_events_single_dataset(X_data,y_data,weights_data)

#bbggTrees have by default signal and CR events, let's be sure that we clean it
X_bkg,y_bkg,weights_bkg,X_sig,y_sig,weights_sig=preprocessing.clean_signal_events(X_bkg,y_bkg,weights_bkg,X_sig,y_sig,weights_sig)

#np.savetxt('/tmp/micheli/xbkg.txt',X_bkg)
#preprocessing.adjust_and_compress(utils.IO.background_df[0]).to_csv('/tmp/micheli/bkg.csv')


['absCosThetaStar_CS', 'absCosTheta_bb', 'absCosTheta_gg', 'PhoJetMinDr', 'customLeadingPhotonIDMVA', 'customSubLeadingPhotonIDMVA', 'leadingJet_DeepCSV', 'subleadingJet_DeepCSV', 'leadingPhotonSigOverE', 'subleadingPhotonSigOverE', 'sigmaMOverM', 'diphotonCandidatePtOverdiHiggsM', 'dijetCandidatePtOverdiHiggsM', 'leadingJet_bRegNNResolution', 'subleadingJet_bRegNNResolution', 'noexpand:sigmaMJets/Mjj']
using tree:bbggSelectionTree


In [4]:
# load the model from disk
from sklearn.externals import joblib
#loaded_model = joblib.load(os.path.expanduser('~/HHbbgg_ETH_devel/Training/output_files/allMC_resWeighting_F_noDR_minDRGJet.pkl'))
#loaded_model = joblib.load(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/output_files/simlple_Test_binary.pkl'))
#st
loaded_model = joblib.load(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/plots/st_MCbkg/simlple_Test_binary_st.pkl'))
#st with add ptMgg
#loaded_model = joblib.load(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/plots/st_ptmgg_MCbkg/simlple_Test_binary_st.pkl'))
#st with add ptMgg+ptMjj+dR
#loaded_model = joblib.load(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/plots/st_ptmgg_ptmjj_r_MCbkg/simlple_Test_binary_st.pkl'))

print len(utils.IO.backgroundName)
bkg = []
for i in range(0,len(utils.IO.backgroundName)-1): 
    print "bkg n:"+str(i)
    print X_bkg[y_bkg ==-i-1]
    bkg.append(X_bkg[y_bkg ==-i-1])


Y_pred_sig = loaded_model.predict_proba(X_sig)[:,loaded_model.n_classes_-1].astype(np.float64)
print Y_pred_sig 
Y_pred_bkg = []
for i in range(0,len(utils.IO.backgroundName)-1):  
    print i
    Y_pred_bkg.append(loaded_model.predict_proba(bkg[i])[:,loaded_model.n_classes_-1].astype(np.float64))
#Y_pred_bkg = loaded_model.predict_proba(X_bkg)[:,loaded_model.n_classes_-1].astype(np.float64)

Y_pred_data = loaded_model.predict_proba(X_data)[:,loaded_model.n_classes_-1].astype(np.float64)
print Y_pred_data 

3
bkg n:0
[[2.2119e-01 4.7644e-01 1.1353e-01 ... 1.0899e-01 1.7727e-01 1.3300e-03]
 [2.3854e-01 9.5990e-02 8.3316e-01 ... 1.8306e-01 2.0960e-01 1.3400e-03]
 [9.8966e-01 8.2253e-01 5.5952e-01 ... 1.8843e-01 2.3501e-01 1.2200e-03]
 ...
 [8.7899e-01 8.4999e-01 1.7474e-01 ... 7.4670e-02 1.2272e-01 8.3000e-04]
 [6.8217e-01 7.1715e-01 4.8720e-01 ... 1.1565e-01 1.2722e-01 1.1700e-03]
 [8.8682e-01 1.0089e-01 6.3458e-01 ... 1.4684e-01 2.2737e-01 1.3400e-03]]
bkg n:1
[[9.9026e-01 5.6159e-01 8.0018e-01 ... 1.3113e-01 1.9154e-01 1.4000e-03]
 [9.5891e-01 3.3826e-01 6.2518e-01 ... 8.3750e-02 1.3325e-01 1.0700e-03]
 [9.9282e-01 7.4376e-01 6.4932e-01 ... 1.5585e-01 1.5220e-01 1.1900e-03]
 ...
 [5.3567e-01 3.3536e-01 9.7200e-03 ... 1.3058e-01 2.4426e-01 1.9100e-03]
 [1.2440e-02 7.1980e-02 5.5980e-01 ... 5.6430e-02 1.6635e-01 6.1000e-04]
 [9.5584e-01 7.9608e-01 6.6779e-01 ... 1.3554e-01 2.6176e-01 1.1900e-03]]
[0.99687362 0.99710578 0.99812561 ... 0.96513414 0.98242235 0.94441837]
0
1
[0.01019972 0.0140

In [5]:
#define MVA cut and additional variables needed
import os
#st
additionalCut_names = 'noexpand:leadingPhoton_pt/CMS_hgg_mass,noexpand:subleadingPhoton_pt/CMS_hgg_mass,MX'.split(",")
#st + ptMjj+dR
#additionalCut_names = 'MX'.split(",")
#additionalCut_names = 'noexpand:diphotonCandidate.M(),noexpand:dijetCandidate.M(),MX,isSignal'.split(",")
#additionalCut_names += 'HHTagger2017'.split(",")
outTag = 'output_files'
outDir=os.path.expanduser("/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/"+outTag)
if not os.path.exists(outDir):
    os.mkdir(outDir)

In [6]:
sig_count_df = rpd.read_root(utils.IO.signalName[0],"bbggSelectionTree", columns = branch_names+additionalCut_names)
preprocessing.define_process_weight(sig_count_df,utils.IO.sigProc[0],utils.IO.signalName[0])

#nTot is a multidim vector with all additional variables, dictVar is a dictionary associating a name of the variable
#to a position in the vector
nTot,dictVar = postprocessing.stackFeatures(sig_count_df,branch_names+additionalCut_names)
#apply isSignal cleaning
nCleaned = nTot[np.where(nTot[:,dictVar['weight']]!=0),:][0]
print "Y_pred"
print Y_pred_sig.shape

#it's a stupid way to save also mva output after cuts, more efficient solutions should be found
Y_pred_total = np.column_stack((nCleaned,Y_pred_sig))

processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.signalName[0].split("/")[len(utils.IO.signalName[0].split("/"))-1].replace("output_","").replace(".root","")+"_preselection"+".root"
postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_sig)

processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.signalName[0].split("/")[len(utils.IO.signalName[0].split("/"))-1].replace("output_","").replace(".root","")+"_preselection_diffNaming"+".root"
postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_sig,nameTree="reducedTree_sig")


Y_pred
(121837,)


In [7]:
## do gJets not in the loop since they have two samples for one process
bkg_1_count_df = rpd.read_root(utils.IO.backgroundName[1],"bbggSelectionTree", columns = branch_names+additionalCut_names)
preprocessing.define_process_weight(bkg_1_count_df,utils.IO.bkgProc[1],utils.IO.backgroundName[1])

crazySF_20=25
nTot,dictVar = postprocessing.stackFeatures(bkg_1_count_df,branch_names+additionalCut_names,SF=crazySF_20)

print nTot.shape

bkg_2_count_df = rpd.read_root(utils.IO.backgroundName[2],"bbggSelectionTree", columns = branch_names+additionalCut_names)
preprocessing.define_process_weight(bkg_2_count_df,utils.IO.bkgProc[2],utils.IO.backgroundName[2])

crazySF_40=3
nTot_2,dictVar = postprocessing.stackFeatures(bkg_2_count_df,branch_names+additionalCut_names,SF=crazySF_40)

nTot_3 = np.concatenate((nTot,nTot_2))
#nTot_3 = nTot

print nTot_3.shape
#apply isSignal cleaning
nCleaned = nTot_3[np.where(nTot_3[:,dictVar['weight']]!=0),:][0]
print "nCleaned"
print nCleaned.shape

processPath=(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.backgroundName[1].split("/")[len(utils.IO.backgroundName[1].split("/"))-1].replace("output_","").replace(".root","")+"_preselection"+".root").replace("_Pt-20to40","")
postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_bkg[1])
#postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_bkg)

processPath=(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.backgroundName[1].split("/")[len(utils.IO.backgroundName[1].split("/"))-1].replace("output_","").replace(".root","")+"_preselection_diffNaming"+".root").replace("_Pt-20to40","")
#postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_bkg,nameTree="reducedTree_bkg_2")
postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_bkg[1],nameTree="reducedTree_bkg_2")


(1262, 20)
(75721, 20)
nCleaned
(75721, 20)


In [8]:
for iProcess in range(0,len(utils.IO.backgroundName)):
    ##gJets which are two samples for one process are skipped
    iSample=iProcess
    if iProcess == 1 or iProcess ==2:
            continue
    if iProcess > 2:
        iSample = iProcess-1
    
    print "Processing sample: "+str(iProcess)
    bkg_count_df = rpd.read_root(utils.IO.backgroundName[iProcess],"bbggSelectionTree", columns = branch_names+additionalCut_names)
    preprocessing.define_process_weight(bkg_count_df,utils.IO.bkgProc[iProcess],utils.IO.backgroundName[iProcess])

    crazySF=1
    ##scale diphoton + jets
    if iProcess == 0:
        crazySF=1.45
    nTot,dictVar = postprocessing.stackFeatures(bkg_count_df,branch_names+additionalCut_names,SF=crazySF)


    nCleaned = nTot[np.where(nTot[:,dictVar['weight']]!=0),:][0]
    print "nCleaned"
    print nCleaned.shape

    processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.backgroundName[iProcess].split("/")[len(utils.IO.backgroundName[2].split("/"))-1].replace("output_","").replace(".root","")+"_preselection"+".root"
    postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_bkg[iSample])    
#    processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.backgroundName[iProcess].split("/")[len(utils.IO.backgroundName[0].split("/"))-1].replace("output_","").replace(".root","")+"_preselection"+".root"
#    postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_bkg)

    processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.backgroundName[iProcess].split("/")[len(utils.IO.backgroundName[2].split("/"))-1].replace("output_","").replace(".root","")+"_preselection_diffNaming"+".root"
    #processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.backgroundName[iProcess].split("/")[len(utils.IO.backgroundName[0].split("/"))-1].replace("output_","").replace(".root","")+"_preselection_diffNaming"+".root"
#    if "GluGluToHHTo2B2G_node_"in processPath:
    if "GluGluToHHTo2B2G_node_SM_13TeV_madgraph_13TeV_DoubleHTag_0"in processPath:
        treeName = "reducedTree_sig_node_"+str(iProcess-6)
    else:
        treeName = "reducedTree_bkg_"+str(iProcess)
    
    postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_bkg[iSample],nameTree=treeName)    
#    postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_bkg,nameTree=treeName)

Processing sample: 0
nCleaned
(1482238, 20)


In [9]:
data_count_df = rpd.read_root(utils.IO.dataName[0],"bbggSelectionTree", columns = branch_names+additionalCut_names)

nTot,dictVar = postprocessing.stackFeatures(data_count_df,branch_names+additionalCut_names,isData=1)

#apply isSignal cleaning
#nCleaned = nTot[np.where(nTot[:,dictVar['weight']]!=0),:][0]
#print "nCleaned"
#print nCleaned.shape
#print Y_pred_data.shape

#save preselection data
#processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.dataName[0].split("/")[len(utils.IO.dataName[0].split("/"))-1].replace("output_","").replace(".root","")+"_preselection"+".root"
#postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_data)

#processPath=os.path.expanduser('~/HHbbgg_ETH_devel/outfiles/')+outTag+'/'+utils.IO.dataName[0].split("/")[len(utils.IO.dataName[0].split("/"))-1].replace("output_","").replace(".root","")+"_preselection_diffNaming"+".root"
#postprocessing.saveTree(processPath,dictVar,nCleaned,Y_pred_data,nameTree="reducedTree_bkg")

nCleaned
(269198, 20)
(269198,)


IOError: cannot open file /home/ovtin/HHbbgg_ETH_devel/outfiles/output_files/DoubleEG_2017_st_cuts_preselection_diffNaming.root

SysError in <TFile::TFile>: file /home/ovtin/HHbbgg_ETH_devel/outfiles/output_files/DoubleEG_2017_st_cuts_preselection_diffNaming.root can not be opened (No such file or directory)


In [ ]:
#from subprocess import call
#call(["hadd","daje.root *diffNaming.root"])
print "cd "+os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag
os.system('hadd '+ os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+'Total_preselection_diffNaming.root '+ os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+'*diffNaming.root')