In [1]:
import os
import sys; sys.path.append("/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/python") # to load packages
import training_utils as utils
import numpy as np
reload(utils)
import preprocessing_utils as preprocessing
reload(preprocessing)
import plotting_utils as plotting
reload(plotting)
import optimization_utils as optimization
reload(optimization)
import postprocessing_utils as postprocessing
reload(postprocessing)


Welcome to JupyROOT 6.13/02


<module 'postprocessing_utils' from '/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/python/postprocessing_utils.pyc'>

In [2]:
reload(utils)
reload(preprocessing)
reload(plotting)
reload(optimization)
reload(postprocessing)
#ntuples = '2016'
#ntuples = '2017'
ntuples = '2017/flattrees_st_cuts'
#ntuples = '2017/flattrees_st_cuts_ptMjj'
# "%" sign allows to interpret the rest as a system command
%env data=$utils.IO.ldata$ntuples
files = ! ls $data | sort -t_ -k 3 -n
#pick only SM
#signal = [s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_2016.root" in s]
#diphotonJets = [s for s in files if "DoubleEG_2016.root" in s]
#signal = [s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_2017.root" in s]
#
#signal = [s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_st_cuts.root" in s]
#diphotonJets = [s for s in files if "output_DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa_st_cuts.root" in s]
#gJets_lowPt = [s for s in files if "output_GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts.root" in s]
#gJets_highPt = [s for s in files if "output_GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts.root" in s]
#
#signal = [s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_st_cuts_ptMjj.root" in s]
#diphotonJets = [s for s in files if "output_DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa_st_cuts_ptMjj.root" in s]
#gJets_lowPt = [s for s in files if "output_GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts_ptMjj.root" in s]
#gJets_highPt = [s for s in files if "output_GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts_ptMjj.root" in s]
#
signal = [s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_st_cuts" in s]
diphotonJets = [s for s in files if "output_DiPhotonJetsBox_" in s]
gJets_lowPt = [s for s in files if "output_GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts" in s]
gJets_highPt = [s for s in files if "output_GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cut" in s]
ggH = [s for s in files if "output_GluGluHToGG_" in s]
vbf = [s for s in files if "output_VBFHToGG_M-125_13TeV_powheg_pythia8_st_cuts" in s]
VH = [s for s in files if "output_VHToGG_" in s]
bbH = [s for s in files if "output_bbHToGG_M-125_4FS_yb2" in s] #is this correct?
ttH = [s for s in files if "output_ttHToGG_" in s]
vbf2 = [s for s in files if "output_VBFHToGG_M125_13TeV_amcatnlo_pythia8_st_cuts" in s]

Data= [s for s in files if "DoubleEG_2017_st_cuts" in s]

utils.IO.add_signal(ntuples,signal,1)
print diphotonJets
utils.IO.add_background(ntuples,diphotonJets,-1)
utils.IO.add_background(ntuples,gJets_lowPt,-2)
utils.IO.add_background(ntuples,gJets_highPt,-2)
utils.IO.add_background(ntuples,ggH,-3)
utils.IO.add_background(ntuples,vbf,-4)
utils.IO.add_background(ntuples,VH,-5)
utils.IO.add_background(ntuples,bbH,-6)
utils.IO.add_background(ntuples,ttH,-7)
utils.IO.add_background(ntuples,vbf2,-8)

nBkg = len(utils.IO.backgroundName)
print nBkg

utils.IO.add_data(ntuples,Data,-10)

#add all nodes
nodes = []
#for i in range(2,14):
#    nodes.append([s for s in files if "output_GluGluToHHTo2B2G_node_SM_13TeV-madgraph_2016"+str(i) in s])
##    nodes.append([s for s in files if "GluGluToHHTo2B2G_node_"+str(i) in s])
for i in range(len(utils.IO.backgroundName),len(utils.IO.backgroundName)+len(nodes)):
    utils.IO.add_background(ntuples,nodes[i-nBkg],-i) 
    

for i in range(len(utils.IO.backgroundName)):        
    print "using background file n."+str(i)+": "+utils.IO.backgroundName[i]
for i in range(len(utils.IO.signalName)):    
    print "using signal file n."+str(i)+": "+utils.IO.signalName[i]
print "using data file: "+ utils.IO.dataName[0]


env: data=/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/flattrees_st_cuts
['output_DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa_st_cuts.root']
11
using background file n.0: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/flattrees_st_cuts/output_DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa_st_cuts.root
using background file n.1: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/flattrees_st_cuts/output_GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts.root
using background file n.2: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/flattrees_st_cuts/output_GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts.root
using background file n.3: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/flattrees_st_cuts/output_GluGluHToGG_M-125_13TeV_powheg_pythia8_st_cuts.root
using background file n.4: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/2017/flattrees_st_cuts/output_VBFHToGG_M-125_13TeV_powheg_pyt

In [3]:
#use noexpand for root expressions, it needs this file https://github.com/ibab/root_pandas/blob/master/root_pandas/readwrite.py
#all the branches you want to save in new trees
#standart of input values 
#branch_names = 'absCosThetaStar_CS,absCosTheta_bb,absCosTheta_gg,PhoJetMinDr,customLeadingPhotonIDMVA,customSubLeadingPhotonIDMVA,leadingJet_DeepCSV,subleadingJet_DeepCSV,leadingPhotonSigOverE,subleadingPhotonSigOverE,sigmaMOverM,diphotonCandidatePtOverdiHiggsM,dijetCandidatePtOverdiHiggsM,leadingJet_bRegNNResolution,subleadingJet_bRegNNResolution,noexpand:sigmaMJets/Mjj'.split(",")
#st values with adding pt_gg/m_gg
#branch_names = 'absCosThetaStar_CS,absCosTheta_bb,absCosTheta_gg,PhoJetMinDr,customLeadingPhotonIDMVA,customSubLeadingPhotonIDMVA,leadingJet_DeepCSV,subleadingJet_DeepCSV,leadingPhotonSigOverE,subleadingPhotonSigOverE,sigmaMOverM,diphotonCandidatePtOverdiHiggsM,dijetCandidatePtOverdiHiggsM,leadingJet_bRegNNResolution,subleadingJet_bRegNNResolution,noexpand:sigmaMJets/Mjj,noexpand:leadingPhoton_pt/CMS_hgg_mass,noexpand:subleadingPhoton_pt/CMS_hgg_mass'.split(",")
#st values with adding pt_gg/m_gg, pt_jj/M_jj
branch_names = 'absCosThetaStar_CS,absCosTheta_bb,absCosTheta_gg,PhoJetMinDr,customLeadingPhotonIDMVA,customSubLeadingPhotonIDMVA,leadingJet_DeepCSV,subleadingJet_DeepCSV,leadingPhotonSigOverE,subleadingPhotonSigOverE,sigmaMOverM,diphotonCandidatePtOverdiHiggsM,dijetCandidatePtOverdiHiggsM,leadingJet_bRegNNResolution,subleadingJet_bRegNNResolution,noexpand:sigmaMJets/Mjj,noexpand:leadingPhoton_pt/CMS_hgg_mass,noexpand:subleadingPhoton_pt/CMS_hgg_mass,noexpand:leadingJet_pt/Mjj,noexpand:subleadingJet_pt/Mjj,PhoJetotherDr'.split(",")

branch_names = [c.strip() for c in branch_names]
print branch_names

import pandas as pd  
import root_pandas as rpd

# no need to shuffle here, we just count events
preprocessing.set_signals_and_backgrounds("bbggSelectionTree",branch_names,shuffle=False)
X_bkg,y_bkg,weights_bkg,X_sig,y_sig,weights_sig=preprocessing.set_variables(branch_names)

X_data,y_data,weights_data = preprocessing.set_data("bbggSelectionTree",branch_names)
X_data,y_data,weights_data = preprocessing.clean_signal_events_single_dataset(X_data,y_data,weights_data)

#bbggTrees have by default signal and CR events, let's be sure that we clean it
X_bkg,y_bkg,weights_bkg,X_sig,y_sig,weights_sig=preprocessing.clean_signal_events(X_bkg,y_bkg,weights_bkg,X_sig,y_sig,weights_sig)

#np.savetxt('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/xbkg.txt',X_bkg)
#np.savetxt('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/weightsbkg.txt',weights_bkg)
#preprocessing.adjust_and_compress(utils.IO.background_df[0]).to_csv('/tmp/micheli/bkg.csv')


['absCosThetaStar_CS', 'absCosTheta_bb', 'absCosTheta_gg', 'PhoJetMinDr', 'customLeadingPhotonIDMVA', 'customSubLeadingPhotonIDMVA', 'leadingJet_DeepCSV', 'subleadingJet_DeepCSV', 'leadingPhotonSigOverE', 'subleadingPhotonSigOverE', 'sigmaMOverM', 'diphotonCandidatePtOverdiHiggsM', 'dijetCandidatePtOverdiHiggsM', 'leadingJet_bRegNNResolution', 'subleadingJet_bRegNNResolution', 'noexpand:sigmaMJets/Mjj', 'noexpand:leadingPhoton_pt/CMS_hgg_mass', 'noexpand:subleadingPhoton_pt/CMS_hgg_mass', 'noexpand:leadingJet_pt/Mjj', 'noexpand:subleadingJet_pt/Mjj', 'PhoJetotherDr']
using tree:bbggSelectionTree


In [4]:
# load the model from disk
from sklearn.externals import joblib
#st
#loaded_model = joblib.load(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/plots/st_MCbkg/simlple_Test_binary_st.pkl'))
#st with add ptMgg
#loaded_model = joblib.load(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/plots/st_ptmgg_MCbkg/simlple_Test_binary_st.pkl'))
#st with add ptMgg+ptMjj+dR
#loaded_model = joblib.load(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/plots/st_ptmgg_ptmjj_r_MCbkg/simlple_Test_binary_st.pkl'))
#
#st
#loaded_model = joblib.load(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/plots/optimization/st_MC_Bkg_lxplus/simlple_Test_binary_st.pkl'))
#st with add ptMgg
#loaded_model = joblib.load(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/plots/optimization/st_MC_Bkg_ptmgg_lxplus/simlple_Test_binary_st.pkl'))
#st with add ptMgg+ptMjj+dR
loaded_model = joblib.load(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/plots/optimization/st_MC_Bkg_ptmgg_ptmjj_dR_lxplus/simlple_Test_binary_st.pkl'))


print len(utils.IO.backgroundName)
bkg = []
for i in range(0,len(utils.IO.backgroundName)-1): 
    print "bkg n:"+str(i)
    print X_bkg[y_bkg ==-i-1]
    bkg.append(X_bkg[y_bkg ==-i-1])

#compute the MVA
Y_pred_sig = loaded_model.predict_proba(X_sig)[:,loaded_model.n_classes_-1].astype(np.float64)
print Y_pred_sig 
Y_pred_bkg = []
for i in range(0,len(utils.IO.backgroundName)-1):  
    print i
    Y_pred_bkg.append(loaded_model.predict_proba(bkg[i])[:,loaded_model.n_classes_-1].astype(np.float64))

Y_pred_data = loaded_model.predict_proba(X_data)[:,loaded_model.n_classes_-1].astype(np.float64)
print Y_pred_data 

11
bkg n:0
[[0.22119 0.47644 0.11353 ... 0.53364 0.52329 1.56064]
 [0.23854 0.09599 0.83316 ... 0.55733 0.52815 2.70928]
 [0.98966 0.82253 0.55952 ... 0.34747 0.23024 2.02816]
 ...
 [0.87899 0.84999 0.17474 ... 0.88542 0.3459  3.3885 ]
 [0.68217 0.71715 0.4872  ... 0.90933 0.44481 2.70307]
 [0.88682 0.10089 0.63458 ... 0.69589 0.33051 2.39649]]
bkg n:1
[[0.99026 0.56159 0.80018 ... 0.48841 0.38174 2.39476]
 [0.95891 0.33826 0.62518 ... 0.60297 0.36319 2.50875]
 [0.99282 0.74376 0.64932 ... 0.37277 0.3107  2.86086]
 ...
 [0.53567 0.33536 0.00972 ... 0.79105 0.44961 1.62003]
 [0.01244 0.07198 0.5598  ... 0.98059 0.23855 2.09346]
 [0.95584 0.79608 0.66779 ... 0.39239 0.21982 2.14914]]
bkg n:2
[[0.96586 0.204   0.67435 ... 0.61189 0.40944 3.30991]
 [0.95904 0.93875 0.2944  ... 0.53244 0.32311 4.32613]
 [0.90743 0.99091 0.64387 ... 0.36039 0.15274 4.14145]
 ...
 [0.96871 0.02429 0.23172 ... 0.6847  0.32745 3.17478]
 [0.64873 0.85294 0.35603 ... 0.41521 0.33777 2.21154]
 [0.24676 0.99263 0.6

In [5]:
#Adding additional variables needed
import os
#st
#additionalCut_names = 'noexpand:leadingPhoton_pt/CMS_hgg_mass,noexpand:subleadingPhoton_pt/CMS_hgg_mass,MX'.split(",")
#st + pt/mgg, OR + ptMjj+dR
additionalCut_names = 'MX'.split(",")
#additionalCut_names = 'noexpand:diphotonCandidate.M(),noexpand:dijetCandidate.M(),MX,isSignal'.split(",")
#st
#outTag = 'output_files/reduceTree_st_variables'
#st + pt/mgg 
#outTag = 'output_files/reduceTree_st_variables_add_ptmgg'
#st + pt/mgg+pt/mjj+dR 
outTag = 'output_files/reduceTree_st_variables_add_ptmgg_ptmjj_dR'
outDir=os.path.expanduser("/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/"+outTag)
if not os.path.exists(outDir):
    os.mkdir(outDir)

In [6]:
#Save Signal
sig_count_df = rpd.read_root(utils.IO.signalName[0],"bbggSelectionTree", columns = branch_names+additionalCut_names)
preprocessing.define_process_weight(sig_count_df,utils.IO.sigProc[0],utils.IO.signalName[0])

#nTot is a multidim vector with all additional variables, dictVar is a dictionary associating a name of the variable
#to a position in the vector
nTot,dictVar = postprocessing.stackFeatures(sig_count_df,branch_names+additionalCut_names)
print "Y_pred"
print Y_pred_sig.shape

processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.signalName[0].split("/")[len(utils.IO.signalName[0].split("/"))-1].replace("output_","").replace(".root","")+"_preselection"+".root"
postprocessing.saveTree(processPath,dictVar,nTot,Y_pred_sig)

processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.signalName[0].split("/")[len(utils.IO.signalName[0].split("/"))-1].replace("output_","").replace(".root","")+"_preselection_diffNaming"+".root"
postprocessing.saveTree(processPath,dictVar,nTot,Y_pred_sig,nameTree="reducedTree_sig")

Y_pred
(121837,)


In [7]:
# do gJets not in the loop since they have two samples for one process
bkg_1_count_df = rpd.read_root(utils.IO.backgroundName[1],"bbggSelectionTree", columns = branch_names+additionalCut_names)
preprocessing.define_process_weight(bkg_1_count_df,utils.IO.bkgProc[1],utils.IO.backgroundName[1])

nTot,dictVar = postprocessing.stackFeatures(bkg_1_count_df,branch_names+additionalCut_names)
print nTot.shape

bkg_2_count_df = rpd.read_root(utils.IO.backgroundName[2],"bbggSelectionTree", columns = branch_names+additionalCut_names)
preprocessing.define_process_weight(bkg_2_count_df,utils.IO.bkgProc[2],utils.IO.backgroundName[2])

nTot_2,dictVar = postprocessing.stackFeatures(bkg_2_count_df,branch_names+additionalCut_names)

nTot_3 = np.concatenate((nTot,nTot_2))
print nTot_3.shape

processPath=(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.backgroundName[1].split("/")[len(utils.IO.backgroundName[1].split("/"))-1].replace("output_","").replace(".root","")+"_preselection"+".root").replace("_Pt-20to40","")
postprocessing.saveTree(processPath,dictVar,nTot_3,Y_pred_bkg[1])

processPath=(os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.backgroundName[1].split("/")[len(utils.IO.backgroundName[1].split("/"))-1].replace("output_","").replace(".root","")+"_preselection_diffNaming"+".root").replace("_Pt-20to40","")
postprocessing.saveTree(processPath,dictVar,nTot_3,Y_pred_bkg[1],nameTree="reducedTree_bkg_2")


(1262, 23)
(75721, 23)


In [8]:
#Bkgs in the loop - diphotJets and another
for iProcess in range(0,len(utils.IO.backgroundName)):
    ##gJets which are two samples for one process are skipped  !not skipped
    iSample=iProcess
    if iProcess == 1 or iProcess ==2:
            continue
    if iProcess > 2:
        iSample = iProcess-1
    
    print "Processing sample: "+str(iProcess)
    bkg_count_df = rpd.read_root(utils.IO.backgroundName[iProcess],"bbggSelectionTree", columns = branch_names+additionalCut_names)
    preprocessing.define_process_weight(bkg_count_df,utils.IO.bkgProc[iProcess],utils.IO.backgroundName[iProcess])

    nTot,dictVar = postprocessing.stackFeatures(bkg_count_df,branch_names+additionalCut_names)

    processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.backgroundName[iProcess].split("/")[len(utils.IO.backgroundName[7].split("/"))-1].replace("output_","").replace(".root","")+"_preselection"+".root"
    postprocessing.saveTree(processPath,dictVar,nTot,Y_pred_bkg[iSample])    

    processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.backgroundName[iProcess].split("/")[len(utils.IO.backgroundName[7].split("/"))-1].replace("output_","").replace(".root","")+"_preselection_diffNaming"+".root"
    if "GluGluToHHTo2B2G_node_SM_13TeV_madgraph_13TeV_DoubleHTag_0"in processPath:
        treeName = "reducedTree_sig_node_"+str(iProcess-6)
    else:
        treeName = "reducedTree_bkg_"+str(iProcess)
    
    postprocessing.saveTree(processPath,dictVar,nTot,Y_pred_bkg[iSample],nameTree=treeName)    


Processing sample: 0
Processing sample: 3
Processing sample: 4
Processing sample: 5
Processing sample: 6
Processing sample: 7
Processing sample: 8
Processing sample: 9
Processing sample: 10


In [9]:
#save Data
data_count_df = rpd.read_root(utils.IO.dataName[0],"bbggSelectionTree", columns = branch_names+additionalCut_names)

nTot,dictVar = postprocessing.stackFeatures(data_count_df,branch_names+additionalCut_names,isData=1)

#save preselection data
processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.dataName[0].split("/")[len(utils.IO.dataName[0].split("/"))-1].replace("output_","").replace(".root","")+"_preselection"+".root"
postprocessing.saveTree(processPath,dictVar,nTot,Y_pred_data)

processPath=os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+utils.IO.dataName[0].split("/")[len(utils.IO.dataName[0].split("/"))-1].replace("output_","").replace(".root","")+"_preselection_diffNaming"+".root"
postprocessing.saveTree(processPath,dictVar,nTot,Y_pred_data,nameTree="reducedTree_bkg")

In [10]:
#from subprocess import call
#call(["hadd","daje.root *diffNaming.root"])
print "cd "+os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag
os.system('hadd '+ os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+'Total_preselection_diffNaming.root '+ os.path.expanduser('/home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/')+outTag+'/'+'*diffNaming.root')

cd /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/output_files/reduceTree_st_variables_add_ptmgg_ptmjj_dR


0

hadd Target file: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/output_files/reduceTree_st_variables_add_ptmgg_ptmjj_dR/Total_preselection_diffNaming.root
hadd compression setting for all ouput: 4
hadd Source file 1: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/output_files/reduceTree_st_variables_add_ptmgg_ptmjj_dR/DiPhotonJetsBox_MGG-80toInf_13TeV-Sherpa_st_cuts_preselection_diffNaming.root
hadd Source file 2: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/output_files/reduceTree_st_variables_add_ptmgg_ptmjj_dR/DoubleEG_2017_st_cuts_preselection_diffNaming.root
hadd Source file 3: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/output_files/reduceTree_st_variables_add_ptmgg_ptmjj_dR/GJet_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_Pythia8_st_cuts_preselection_diffNaming.root
hadd Source file 4: /home/ovtin/cernbox/HHggbb/HHbbgg_ETH_devel/Training/output_files/reduceTree_st_variables_add_ptmgg_ptmjj_dR/GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_13TeV_